version: '3.8'

services:
  db:
    image: postgres:14-alpine3.15
    container_name: "goods_storage_pg"
    environment:
      - "POSTGRES_DB=goods_storage"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
